- ultravox/data/datasets.py
- ultravox/training/config_base.py
- ultravox/training/configs/meta_config.yaml
- ultravox/training/ddp_utils.py
- ultravox/training/ddp_utils_test.py
- ultravox/training/evaluation.py
- ultravox/training/train.py
This PR does the following:
- Bugfix: AnyInstruct was not using val/train splits (as it had somehow gotten removed from the last PR)
- Faster evaluations by using DDP multiprocessing for text generation
- Validation loss added by default to training
> Improved Evaluations

- requirements.txt
- ultravox/training/train.py
With the recent patch from [HF Transformers for Wav2Vec2](https://x.com/kamilakesbi/status/1782780288243749186), we can train the audio encoder, whether it's wav2vec2 or Whisper, with bfloat16, so there's no need to have an exception for it.
This change seems to have landed on 4.40.2 (as verified by an experiment and the timing between the PR merge and PyPi version), so I'm increasing our minimum requirement for it:
W&B task for verification:
https://wandb.ai/fixie/ultravox/runs/lygf6hbn/overview
> Audio Encoder to bfloat16

- README.md
- ultravox/tools/infer_tool.py
Fixes the default HF model name. On HF model is named [fixie-ai/ultravox](https://huggingface.co/fixie-ai/ultravox) and not [fixie-ai/ultravox-v0.1](https://huggingface.co/search/full-text?q=%22fixie-ai%2Fultravox-v0.1%22&type=model).
Also fixes small misspelling for the env setup for `just` : The `create-env` command does not exist but `create-venv` does :-).
> Fixes the default HF model name

- README.md
The previous page says it has been deprecated in favor of this one.
https://huggingface.co/fixie-ai/ultravox
> Update Hugging Face link

- Justfile
- mcloud.yaml
- mypy.ini
- requirements.txt
- ultravox/model/ultravox_processing.py
- ultravox/training/configs/llama3_whisper.yaml
- ultravox/training/train.py
No longer needed since we're doing everything on W&B. Also cleaned up some other old cruft.
> Remove mlflow dependency

- ultravox/tools/ds_tool.py
Also:
- makes the task name positional
- defaults subset to None, as not every default is "default"
- refactors the map func to be inside the task, making tasks more encapsulated
> Add @file syntax to ds_tool

- ultravox/data/datasets.py
- ultravox/data/datasets_test.py
We saw `VoiceSample` failing the assert on `float32` audio data when playing around with the Gradio infer app and submitting an `mp3` file. We didn't dig deeper into Gradio (I'm sure it's possible to alter/convert there as well), but it seems potentially useful for `VoiceSample` to handle `int16` audio data on top of what it already handles.
> datasets: Handle converting `int16` audio data in `VoiceSample`.

- ultravox/tools/ds_tool.py
- ultravox/tools/tts.py
TTS impl is controlled by the `-i` argument.
LLM impl is controlled by the `-b` and `-k` arguments.
Also support random voices via the `-V random` argument.
> Add Eleven and Fireworks support to ds_tool

- ultravox/tools/ds_tool.py
- ultravox/tools/ds_tool/ds_tool.py
- ultravox/tools/infer_tool.py
- ultravox/tools/tts.py
- --upload_split param to allow the dest split to be different than the src split
- allow @file syntax for --prompt
- add retries and timeouts to TTS requests
> Minor fixes to ds_tool and infer_tool

- ultravox/data/datasets.py
- ultravox/data/datasets_test.py
- ultravox/inference/infer_test.py
- ultravox/model/data_processing.py
- ultravox/model/ultravox_processing.py
- ultravox/tools/gradio_demo.py
- ultravox/tools/infer_tool.py
- ultravox/training/config_base.py
- ultravox/training/configs/meta_config.yaml
- ultravox/training/train.py
This PR separates validation data_sets from training data_sets and adds separate evaluations for the following datasets both in the audio and text-only modes: `["heysquad_human", "anyinstruct", "soda", "peoplespeech"]`
Example perplexity/loss curves:
> More validations

- ultravox/data/datasets.py
Separating the PR to make it easier.
The CoVoST2 dataset can be used by specifying the subset name and no default was used since neither option seemed like a reasonable default.
Examples for setting the dataset as well as the name: `covost2:en_zh-CN` (English to Chinese), `covost:es_en` (Spanish to English).
Related to #50
> CoVoST 2 dataset

- ultravox/tools/infer_tool.py
Previous to [this change](https://github.com/fixie-ai/ultravox/pull/35), it would be possible to say:
```
just infer -f path/to/file.wave
```
or 
```
just infer -f path/to/file.wav --prompt "some prompt"
```
But that broke. 
I have no idea if this is the right fix or not. Happy to run any local tests to verify.
> Make so infer_tools works with a single arg for filename

- ultravox/model/ultravox_model.py
This PR fixes the following:
1. gets rid of the unexpected weights warnings
1. makes HF model loading faster by skipping random initialization
Example of the unexpected weights warning that this PR is supposed to resolve:
```
Some weights of the model checkpoint at fixie-ai/ultravox_dev were not used when initializing UltravoxModel: ['language_model.lm_head.weight', 'language_model.model.embed_tokens.weight', 'language_model.model.layers.0.input_layernorm.weight',
...
- This IS expected if you are initializing UltravoxModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing UltravoxModel from the checkpoint of a model …
```
> HF Model loading fixes

- ultravox/training/evaluation.py
- ultravox/training/train.py
Removes eval sample logs from the main log path to declutter it and they're each written to their own specific file so that they are easier to inspect.
The new files will be stored under the `Files` tab in W&B in a separate `evals` directory.
> Separate files for eval logs

- poetry.lock
- pyproject.toml
- scripts/dataset_creation/tools_audio.sh
- ultravox/tools/ds_tool/caching.py
- ultravox/tools/ds_tool/ds_tool.py
- ultravox/tools/ds_tool/tts.py
- ultravox/tools/ds_tool/user_messages.jinja
This PR allow `ds_tool` to TTS multiple audios with the same voice.
It also adds configs used to create [`fixie-ai/tools-audio`](https://huggingface.co/datasets/fixie-ai/tools-audio) (note: this dataset is likely to be merged into the original `fixie-ai/tools`).
> [ds_tool] Tools with Audio

- mcloud.yaml
- ultravox/data/dataset_config.py
- ultravox/data/datasets.py
- ultravox/training/config_base.py
- ultravox/training/configs/llama3_whisper_kd.yaml
Add GenericVoiceDataset to support new datasets via yaml config, e.g., 
```
data_dicts:
- path: "fixie-ai/librispeech_asr"
name: "clean"
splits:
- "train.100"
- "train.360"
user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
assistant_template: "{{ continuation }}"
transcript_template: "{{ text }}"
num_samples: 100_000
- path: "fixie-ai/librispeech_asr"
name: "other"
splits:
- "train.500"
user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
assistant_template: "{{ continuation }}"
transcript_template: "{{ text }}"
num_samples: 100_000
```
See ultravox.training.configs.llama3_whisper_kd.yaml for example experiment configuration.
> add generic dataset

- ultravox/tools/ds_tool/continuation.jinja
- ultravox/tools/ds_tool/ds_tool.py
1. Fixes TypeError: non-default argument 'template' follows default argument
2. Filters out audio before passed into jinja template to prevent memory spikes when using ds_tool.py
> Fix TypeError: non-default argument 'template' follows default argument, and filter out audio

- Justfile
- ultravox/inference/infer.py
- ultravox/inference/utils.py
- ultravox/tools/gradio_demo.py
- ultravox/tools/gradio_helper.py
Fixes #80 
Now, changes that you make during editing are reflected immediately in the demo. For this to work `demo` has to be a global object, so the `main` function has been removed (as recommended by gradio: https://www.gradio.app/guides/quickstart)
Also adds streaming of output tokens, using `infer_stream` and queueing.
> Live reload for Gradio demo

- ultravox/model/ultravox_model.py
- ultravox/model/ultravox_processing.py
With this PR (assuming the code is updated on HF), we can call `transformers.AutoProcessor.from_pretrained('fixie-ai/ultravox-v0_3')` to get the processor (needed by @petersalas for the VLLM PR).
> Working AutoProcessor.from_pretrained

- ultravox/inference/utils.py
Much faster than float32 and just as fast as float16, on both model loading and generation, thanks to support in macOS 14.
```
% time just infer -v --text_only --prompt count-to-10
poetry run python -m ultravox.tools.infer_tool -v --text_only --prompt count-to-10
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:14<00:00,  3.61s/it]
Q: count-to-10
A: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10. [ttft: 3.56 s, tok: 10, tps: 2.86, tot: 7.06 s]
---
% time just infer -v --text_only --prompt count-to-10 --data_type float16
poetry run python -m ultravox.tools.infer_tool -v --text_only --prompt count-to-10 …
```
> Use bfloat16 by default on MPS

- ultravox/training/train.py
`text_tokenizer.padding_side=right` is used during model training but needs to be changed to `left` (as expected by the `LocalInference` class to support batch inference and for consistency) for model inference at the end of training run.
> Change tokenizer padding_side to left for eval

- ultravox/training/configs/meta_config.yaml
- ultravox/training/train.py
We need to store the model in order to run `do_eval`. With this, `train.py` can be used both as a way to train and as a way to evaluate.
> Make sure do_eval works without do_train

- ultravox/data/dataset_config.py
- ultravox/data/datasets.py
- ultravox/training/train.py
Right now, max steps and epochs will crash with non generic datasets because their size has been set to 0 by default. As a workaround, the default size is set to 1, and an assert is added to check that real sizes are used when training with epoch.
> Assert dataset length when using epochs

- ultravox/model/ultravox_config.py
- ultravox/model/ultravox_config_test.py
As the title suggests, removing `text_config` when `text_model_id` is present, since `text_config` will be overwritten and its existence can be confusing.
This PR is in partial response to this comment on Discord by Hyunsung Lee:
I should note that this PR doesn't quite address this comment, but simply improves another confusion that can arise later down the line when people try to update text_config but see it doesn't actually do anything.
Example config (revision of a private repo): https://huggingface.co/fixie-ai/ultravox-v0_4-llama-3_1-70b/blob/4cfd42ee20b5c2df2065d25a223ff10bfaf0d728/config.json
> Not uploading text_config when text_model_id is present

- mcloud.yaml
- ultravox/training/config_base.py
- ultravox/training/helpers/prefetch_weights.py
- ultravox/training/helpers/prefetch_weights_test.py
- ultravox/training/train.py
This PR allows for downloading the weights of the model first, before starting the DDP processes. The previous approach tends to time out when using 70B model.
> [70B-Part1] Prefetch weights separately

- ultravox/model/ultravox_model.py
- ultravox/training/train.py
The fixes in this PR might not make much sense on their own, but here's what's changing:
1. no_split_modules is getting set dynamically. Apparently the previous approach (of including all possible classes) leads to an error since all classes are expected to be present.
2. `state_dict` and `load_state_dict` logic are slightly modified in how they're applied.
a. using existing register_hook method instead
b. changing `save_pretrained` instead of `state_dict`. TODO: This might end up fixing some of the warnings we were seeing and suppressing as well (not tested yet).
3. `train.py` reverts to using `trainer.save_model` instead of pipeline (in order to work with FSDP), but we will still save the pipeline code and configs.
> [70B-Part2] Improved save model (that can work with FSDP)

- ultravox/model/ultravox_model.py
- ultravox/training/config_base.py
- ultravox/training/train.py
This PR is mostly complete, but I do need to revisit some minor assumptions to make sure I didn't break the normal (non-fsdp) pipeline.
One of the odd changes here is the removal of `.to(device, dtype)`.
- The `dtype` part is moved into the model itself since it'll cost us too much to possibly be sloppy and load a full-precision 70B and then turn it into half precision.
- The `device` part is being handled by the `trainer` itself when doing `trainer.train`. This causes some minor issues (e.g. running `trainer.evaluate` before is not allowed), but they're not hugely important.
- note that now `model.device` is `cpu` (or mps) before `trainer.train` and then `cuda:rank` after `trainer.train`. This might take some getting used to.
> [70B-Part3] FSDP Training

- ultravox/training/config_base.py
- ultravox/training/config_base_test.py
The test for `prefetch_weights.py` assumes that the training config can be created by default. When that fails, it can be very confusing since the user thinks the issue is with `prefetch_weights`, when in fact it's a config issue (whether it's coming from `TrainConfig` or `meta_config.yaml`).
This test won't remove that issue, but at least it makes it easier to figure out where the source of the issue is.
> Create test for config_base.py

- Justfile
- poetry.lock
- pyproject.toml
- ultravox/tools/ds_tool/ds_tool.py
This PR adds a TimestampGeneration task to `ds_tool.py`. It uses [Montreal Forced Aligner (MFA)](https://montreal-forced-aligner.readthedocs.io/en/latest/getting_started.html).
The task adds a new column (e.g. "timestamps") that has word-level alignments in the form of:
```
[ {"start": float in seconds, "end": float in seconds, "text": first word str}, ... ]
```
Usage example:
```bash
just install_mfa
just ds_tool timestamp -d fixie-ai/common_voice_17_0 -S en --upload_name fixie-ai/cv_ts  \
-m english_mfa -T "\"{{text_proc.format_asr_text(sentence)}}\""
```
> Dataset Tool to add Timestamps

- ultravox/training/configs/llama_70b.yaml
Seems like the most important config was missing from the yaml file.
> [bugfix] Missing enable_fsdp in 70b config

- ultravox/model/ultravox_model.py
Since we switched from modifying `state_dict` to modifying `save_pretrained`, the warnings that we'll see when loading the model are going to be different (`transformers` uses keys in `state_dict` to know what has to be there and what shouldn't be there).
This PR updates the keys to be ignored when missing accordingly.
> Update model load warnings

- ultravox/data/__init__.py
- ultravox/data/data_sample.py
- ultravox/data/data_sample_test.py
- ultravox/data/datasets.py
- ultravox/data/datasets_test.py
- ultravox/data/registry.py
- ultravox/data/types.py
- ultravox/inference/base.py
- ultravox/inference/infer.py
- ultravox/inference/infer_test.py
- ultravox/model/data_processing.py
- ultravox/model/data_processing_test.py
- ultravox/tools/data_tool.py
- ultravox/tools/gradio_demo.py
- ultravox/tools/infer_api.py
- ultravox/tools/infer_tool.py
- ultravox/tools/push_to_hub.py
- ultravox/training/config_base.py
- ultravox/training/evaluation.py
- ultravox/training/train.py
This splits out types.py and registry.py to move the list of pre-defined datasets to its own file and avoid circular refs.
An __all__ import is used to minimize changes to surrounding code.
> Break up datasets.py

- ultravox/model/ultravox_model.py
- ultravox/model/ultravox_model_test.py
- ultravox/training/config_base.py
- ultravox/training/configs/meta_config.yaml
- ultravox/training/configs/streaming_tinyllama.yaml
- ultravox/training/train.py
By utilizing a mask, we can simulate audio streaming.
> Audio streaming training with masking

- ultravox/data/__init__.py
- ultravox/data/configs/librispeech.py
- ultravox/data/configs/peoplespeech.py
- ultravox/data/datasets.py
- ultravox/data/datasets_test.py
- ultravox/data/registry.py
- ultravox/data/types.py
- ultravox/training/train.py
- ultravox/utils/monkey_patches.py
We've experienced some issues when training with the basic HF ecosystem. This PR adds some monkey-patches on HF methods (in HF Hub and Datasets) to
1. alleviates issues like time outs or transient connection errors when downloading data
2. make datasets more robust to errors like audio field being empty which was not recoverable without patching
As well as some minor cosmetic changes.
> Training Stability: Patch HF Hub and Datasets methods and update datasets.py

- ultravox/inference/infer.py
I may be wrong, but it is currently not possible to generate an assistant message without first inputting a user message.  This would allow for situations where you might want to generate an assistant message with just a system message prompt.  This PR allows for `sample` to be `None`, provided there are previous messages in the history (such as system messages).  I am not sure if this is the best implementation - so please let me know if it needs any changes!
> Allow response generation with no user message
